name: Daily arXiv Paper Downloader

on:
  push:
    branches:
      - main
  schedule:
    # Runs at 18:00 UTC daily (2:00 AM in Beijing/Singapore time)
    - cron: '0 18 * * *'
  workflow_dispatch:

jobs:
  download:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Grant permission to push to the repo

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Python downloader
        run: python main.py

      - name: Update README.md from paper folder
        run: python update_readme.py

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          # Add all new/modified files. This includes papers, the log file, and README.md.
          git add -A
          # Only commit if there are changes
          if ! git diff-index --quiet HEAD; then
            git commit -m "Automated update: Add new papers and update README"
            git push
          else
            echo "No changes to commit."
          fi

